name: 01 - Building Bloks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Kamil Hello
        run: echo "Hello Kamil"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1
      - name: Say Goodbye
        run: echo "Goodbye Kamil"
