name: 03 - Workflows Runners

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the runner
              run: |
                echo " This job is running on a ${{ runner.os }} runner"
                echo " Runner name: ${{ runner.name }}"
                echo "Runner OS: $RUNNER_OS"
    windows-echo:
      runs-on: windows-latest
      steps:
          - name: Show the runner Windows
            shell: bash
            run: |
              echo " This job is running on a ${{ runner.os }} runner"
              echo " Runner name: ${{ runner.name }}"
              echo "Runner OS: $RUNNER_OS"