name: 06 - Workflow Contexts
on: 
  - workflow_dispatch

env:
  MY_WORKFLOWS_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'from-workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'

    steps:

        - name: Display information
          run: | 
            echo "Event Name: ${{ github.event_name }}"
            echo "Ref: ${{ github.ref }}"
            echo "SHA: ${{ github.sha }}"
            echo "Actor: ${{ github.actor }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Run number ${{ github.run_number }}"

        - name: Retrieve Variable
          run: |
            echo "Variable value: ${{ vars.MY_VAR }}"

        - name: Print Env Variables
          env:
              MY_OVERWRITTEN_VAR: 'step'
          run: |
            echo "Workflow env: ${{ env.MY_WORKFLOWS_VAR}}"
            echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR}}"


        - name: Retrieve Variables
          run: |
            echo "Workflow env: ${{ env.MY_WORKFLOWS_VAR}}"
            echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR}}"