name: 06 Expressions Example
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false


jobs:
  echo-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] expressions'
        if: ${{ inputs.debug}}
        run: |
            echo "Event name: ${{  github.event_name}}"
            echo "Branch: ${{  github.ref  }}"
            echo "Commit SHA: ${{  github.sha  }}"
            echo "Runner OS: ${{  runner.os  }}"

      - name: '[debug] print when Triggered by push'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"