name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: 'I am a workflow variable'
  OVERWRITTEN_VAR: 'from-workflow'

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job variable'
      OVERWRITTEN_VAR: 'from-job'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step variable'
          step_var2: 'I am another step env var'

        run: |
          echo "Variable from env: ${{ env.STEP_VAR }}"
          echo "Step env var 2: $step_var2"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"
      - name: Overwrite job variable
        env:
          OVERWRITTEN_VAR: 'fI have been overwritten at the step level'
        run: |
          echo "Variable from env: ${{ env.STEP_VAR }}"