name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step  
        run: exit 1
      - name: I will be skipped 
        if: ${{ success() }}
        run: echo "I will print if previous steps succed."
      - name: I will be execute
        if: ${{ failure() }}
        run: echo "I will print if previous steps fails."
      - name:  I will be execute
        if: ${{ !cancelled() }}
        run: echo "I will always print if the workflow is not cancelled."
      - name: I will print if the workflow is not cancelled.
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow is not cancelled."

