name: 15 - Working with Matrices

on: 
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }} | Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x,20.x,24.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 24.x
            tag: experimental

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
            node-version: ${{ matrix.node-version }}

      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os }} and Node.js version ${{ matrix.node-version }}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading test results"

  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red,green]
        shape: [circle, square]
        size: [small, large]
        include:
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          - color: red
            shape: triangle
          - opacity: 50
          - color: green
            shape: circle
            size: medium
        exclude:
          - color: green
            shape: circle
            size: large


    steps: 
      - name: Dummy step
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}"