name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}
on: 
  workflow_dispatch:
    inputs:
      target-env:
          type: environment
          default: stating



jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Deploy to Staging"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E tests
        run: |
          echo "Running E2E tests"

  deploy-prod:
    needs: e2e-tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps:
      - name: Echo vars
        run: |
          echo "Deploy to Production"
          