name: 18.2 - Reusable Workflow Example

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflow.yaml
    with:
      target-directory: dummy-directory

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:

      - name: Print Outputs
        run: | 
          echo "Build Status: ${{ needs.deploy.outputs.build-status }}"
          echo "Deployed URL: ${{ needs.deploy.outputs.url }}"